#!/usr/bin/env bash

set -e

# Inspired on https://github.com/adriancooney/Taskfile
#
# Install an alias, to be able to simply execute `run`
# echo 'alias run=./run' >> ~/.aliases
#
# alias run=./Taskfile
# alias help=./Taskfile help

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function default {
    help
}

function build {
    docker-compose -f docker-compose.prod.yml build
}

function liftAgain {
    docker-compose -f docker-compose.prod.yml up -d
}

function migrate {
    docker-compose -f docker-compose.prod.yml exec fax-machine bash -c "php artisan migrate --force"
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-default}"
